{{$PROMETHEUS_SCRAPE_KUBE_PROXY := DefaultParam .PROMETHEUS_SCRAPE_KUBE_PROXY true}}

{{if $PROMETHEUS_SCRAPE_KUBE_PROXY}}
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
subsets:
  - addresses:
    {{range .WorkerIps}}
      - ip: {{.}}
    {{end}}
    ports:
      - name: http-metrics
        port: 10249
        protocol: TCP
{{end}}
