apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-dns-metrics
  name: kube-dns-metrics
  namespace: kube-system
spec:
  ports:
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
  type: ClusterIP
